steps:
  # Install backend dependencies
  - name: 'node:18'
    entrypoint: npm
    args: ['install', '--legacy-peer-deps']
    dir: 'node-version/packages/backend'

  # Install frontend dependencies
  - name: 'node:18'
    entrypoint: npm
    args: ['install', '--legacy-peer-deps']
    dir: 'node-version/packages/frontend'

  # Build backend
  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'build']
    dir: 'node-version/packages/backend'

  # Build frontend
  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'build']
    dir: 'node-version/packages/frontend'

  # Build the backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/backend', '.']
    dir: 'node-version/packages/backend'

  # Build the frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/frontend', '.']
    dir: 'node-version/packages/frontend'

  # Push the backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/backend']

  # Push the frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/frontend']

  # Deploy backend service to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'backend'
      - '--image=gcr.io/${PROJECT_ID}/backend'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--service-account'
      - '967436713449-compute@developer.gserviceaccount.com'
      - '--set-env-vars'
      - 'SPOTIFY_CLIENT_ID=$(gcloud secrets versions access latest --secret=spotify-client-id)'
      - '--set-env-vars'
      - 'SPOTIFY_CLIENT_SECRET=$(gcloud secrets versions access latest --secret=spotify-client-secret)'

  # Deploy frontend service to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'frontend'
      - '--image=gcr.io/${PROJECT_ID}/frontend'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=BACKEND_URL=$(gcloud run services describe backend --region=${_REGION} --format="value(status.url)")/api'

substitutions:
  _REGION: us-central1

serviceAccount: 'projects/${PROJECT_ID}/serviceAccounts/967436713449-compute@developer.gserviceaccount.com'

options:
  logging: CLOUD_LOGGING_ONLY
  env:
    - 'CLOUDSDK_CORE_PROJECT=${PROJECT_ID}'
    - 'GOOGLE_APPLICATION_CREDENTIALS=/workspace/key.json'

images:
  - 'gcr.io/${PROJECT_ID}/backend'
  - 'gcr.io/${PROJECT_ID}/frontend'