steps:
  # Install backend dependencies
  - name: 'node:18'
    entrypoint: npm
    args: ['install']
    dir: 'node-version/packages/backend'

  # Build the backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/backend', '.']
    dir: 'node-version/packages/backend'

  # Build the frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/frontend', '.']
    dir: 'node-version/packages/frontend'

  # Push the backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/backend']

  # Push the frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/frontend']

  # Deploy backend service to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'applemusic-spotify-backend'
      - '--image=us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/backend'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--service-account'
      - 'trae-322@apple-music-to-spotify.iam.gserviceaccount.com'
      - '--set-secrets'
      - 'SPOTIFY_CLIENT_ID=spotify-client-id:latest,SPOTIFY_CLIENT_SECRET=spotify-client-secret:latest'

  # Deploy frontend service to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'applemusic-spotify-frontend'
      - '--image=us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/frontend'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=BACKEND_URL=$(gcloud run services describe applemusic-spotify-backend --region=${_REGION} --format="value(status.url)")/api'

substitutions:
  _REGION: us-central1
  _REPOSITORY: applemusic-spotify-link

serviceAccount: 'projects/${PROJECT_ID}/serviceAccounts/trae-322@apple-music-to-spotify.iam.gserviceaccount.com'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/backend'
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/frontend'