steps:
  # Install backend dependencies and run tests
  - name: 'node:18'
    entrypoint: npm
    args: ['install']
    dir: 'packages/backend'

  - name: 'node:18'
    entrypoint: npm
    args: ['test']
    dir: 'packages/backend'

  # Build the backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/backend', '.']
    dir: 'packages/backend'

  # Build the frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/frontend', '.']
    dir: 'packages/frontend'

  # Push the backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/backend']

  # Push the frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/frontend']

  # Deploy backend service to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'backend'
      - '--image=gcr.io/${PROJECT_ID}/backend'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--service-account'
      - 'trae-322@apple-music-to-spotify.iam.gserviceaccount.com'
      - '--set-secrets'
      - 'SPOTIFY_CLIENT_ID=spotify-client-id:latest,SPOTIFY_CLIENT_SECRET=spotify-client-secret:latest'

  # Deploy frontend service to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'frontend'
      - '--image=gcr.io/${PROJECT_ID}/frontend'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=BACKEND_URL=$(gcloud run services describe backend --region=${_REGION} --format="value(status.url)")/api'

substitutions:
  _REGION: us-central1
  _REPOSITORY: applemusic-spotify-link

serviceAccount: 'projects/${PROJECT_ID}/serviceAccounts/trae-322@apple-music-to-spotify.iam.gserviceaccount.com'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/${PROJECT_ID}/backend'
  - 'gcr.io/${PROJECT_ID}/frontend'