version: '3.8'

services:
  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - BACKEND_URL=http://backend:8080

  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - SPOTIFY_CLIENT_ID_SECRET_NAME=projects/${GOOGLE_CLOUD_PROJECT}/secrets/spotify-client-id/versions/latest
      - SPOTIFY_CLIENT_SECRET_SECRET_NAME=projects/${GOOGLE_CLOUD_PROJECT}/secrets/spotify-client-secret/versions/latest
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3